/*
 * File: app/store/BoxLayouts.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AI.store.BoxLayouts', {
    extend: 'Ext.data.Store',

    requires: [
        'AI.model.Overnested'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'AI.model.Overnested',
            storeId: 'BoxLayouts',
            data: [
                {
                    cmpId: 'CmpId 1',
                    xtype: 'Xtype 1'
                },
                {
                    cmpId: 'CmpId 2',
                    xtype: 'Xtype 2'
                },
                {
                    cmpId: 'CmpId 3',
                    xtype: 'Xtype 3'
                },
                {
                    cmpId: 'CmpId 4',
                    xtype: 'Xtype 4'
                },
                {
                    cmpId: 'CmpId 5',
                    xtype: 'Xtype 5'
                },
                {
                    cmpId: 'CmpId 6',
                    xtype: 'Xtype 6'
                },
                {
                    cmpId: 'CmpId 7',
                    xtype: 'Xtype 7'
                },
                {
                    cmpId: 'CmpId 8',
                    xtype: 'Xtype 8'
                },
                {
                    cmpId: 'CmpId 9',
                    xtype: 'Xtype 9'
                },
                {
                    cmpId: 'CmpId 10',
                    xtype: 'Xtype 10'
                },
                {
                    cmpId: 'CmpId 11',
                    xtype: 'Xtype 11'
                },
                {
                    cmpId: 'CmpId 12',
                    xtype: 'Xtype 12'
                },
                {
                    cmpId: 'CmpId 13',
                    xtype: 'Xtype 13'
                },
                {
                    cmpId: 'CmpId 14',
                    xtype: 'Xtype 14'
                },
                {
                    cmpId: 'CmpId 15',
                    xtype: 'Xtype 15'
                },
                {
                    cmpId: 'CmpId 16',
                    xtype: 'Xtype 16'
                },
                {
                    cmpId: 'CmpId 17',
                    xtype: 'Xtype 17'
                },
                {
                    cmpId: 'CmpId 18',
                    xtype: 'Xtype 18'
                },
                {
                    cmpId: 'CmpId 19',
                    xtype: 'Xtype 19'
                },
                {
                    cmpId: 'CmpId 20',
                    xtype: 'Xtype 20'
                }
            ]
        }, cfg)]);
    }
});