/*
 * File: app/store/mvc/Records.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AI.store.mvc.Records', {
    extend: 'Ext.data.Store',

    requires: [
        'AI.model.Record',
        'AI.store.override.mvc.Records',
        'AI.ux.data.proxy.InspectedWindow'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'AI.model.Record',
            storeId: 'mvc.Records',
            data: [
                {
                    id: 'Id 1'
                },
                {
                    id: 'Id 2'
                },
                {
                    id: 'Id 3'
                },
                {
                    id: 'Id 4'
                },
                {
                    id: 'Id 5'
                },
                {
                    id: 'Id 6'
                },
                {
                    id: 'Id 7'
                },
                {
                    id: 'Id 8'
                },
                {
                    id: 'Id 9'
                },
                {
                    id: 'Id 10'
                },
                {
                    id: 'Id 11'
                },
                {
                    id: 'Id 12'
                },
                {
                    id: 'Id 13'
                },
                {
                    id: 'Id 14'
                },
                {
                    id: 'Id 15'
                },
                {
                    id: 'Id 16'
                },
                {
                    id: 'Id 17'
                },
                {
                    id: 'Id 18'
                },
                {
                    id: 'Id 19'
                },
                {
                    id: 'Id 20'
                }
            ],
            pageSize: 50
        }, cfg)]);
    }
});