/*
 * File: app/store/stores/Stores.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AI.store.stores.Stores', {
    extend: 'Ext.data.Store',

    requires: [
        'AI.model.stores.Store'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'AI.model.stores.Store',
            storeId: 'Stores',
            data: [
                {
                    id: 'Id 1',
                    count: 'Count 1',
                    leaf: false
                },
                {
                    id: 'Id 2',
                    count: 'Count 2',
                    leaf: true
                },
                {
                    id: 'Id 3',
                    count: 'Count 3',
                    leaf: false
                },
                {
                    id: 'Id 4',
                    count: 'Count 4',
                    leaf: false
                },
                {
                    id: 'Id 5',
                    count: 'Count 5',
                    leaf: true
                },
                {
                    id: 'Id 6',
                    count: 'Count 6',
                    leaf: true
                },
                {
                    id: 'Id 7',
                    count: 'Count 7',
                    leaf: false
                },
                {
                    id: 'Id 8',
                    count: 'Count 8',
                    leaf: false
                },
                {
                    id: 'Id 9',
                    count: 'Count 9',
                    leaf: true
                },
                {
                    id: 'Id 10',
                    count: 'Count 10',
                    leaf: false
                },
                {
                    id: 'Id 11',
                    count: 'Count 11',
                    leaf: true
                },
                {
                    id: 'Id 12',
                    count: 'Count 12',
                    leaf: true
                },
                {
                    id: 'Id 13',
                    count: 'Count 13',
                    leaf: true
                },
                {
                    id: 'Id 14',
                    count: 'Count 14',
                    leaf: false
                },
                {
                    id: 'Id 15',
                    count: 'Count 15',
                    leaf: true
                },
                {
                    id: 'Id 16',
                    count: 'Count 16',
                    leaf: false
                },
                {
                    id: 'Id 17',
                    count: 'Count 17',
                    leaf: false
                },
                {
                    id: 'Id 18',
                    count: 'Count 18',
                    leaf: true
                },
                {
                    id: 'Id 19',
                    count: 'Count 19',
                    leaf: true
                },
                {
                    id: 'Id 20',
                    count: 'Count 20',
                    leaf: true
                }
            ]
        }, cfg)]);
    }
});